load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "image_model",
    srcs = ["image_model.go"],
    importpath = "github.com/nacl2000/photo_album/models/image_model",
    visibility = ["//visibility:public"],
)
