load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "user_model",
    srcs = ["user.go"],
    importpath = "github.com/nacl2000/photo_album/models/user_model",
    visibility = ["//visibility:public"],
)
