load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "file",
    srcs = ["file.go"],
    importpath = "github.com/nacl2000/photo_album/pkg/file",
    visibility = ["//visibility:public"],
)
